### ISSUE TITLE
switching underlying branch makes app think it refreshes, but it doesn't

### ISSUE THREAD

**Issue by deitch** [binocarlos/moby-counter#7]
When you run the demo, if you switch the underlying branch using `dm checkout`, and therefore the data set, the front-end UI shows that "progress-bar" (3-4 small rectangles in a line) for a few seconds, indicating it is updating. However, when complete, the same number of logos shows. It doesn't actually update until you do a refresh of the page. It ends up being misleading and makes people think it fails, when the `dm checkout` actually works.

As discussed with @lukemarsden on the slack channel.

**Comment by binocarlos** [comment]
@deitch thanks for the bug report - I've fixed this now in master such that it will remove and refresh data on each reload - thanks!

**Comment by deitch** [comment]
Yep, works great.
